create ok , read ok , delete почти ok
Antoha2/toDo pull request #5
Opened 2022-04-06 05:56 UTC by Antoha2

2022-04-06 07:12 UTC, staszigzag requested changes

2022-04-06 07:12 UTC, staszigzag commented on service/serviceImpl.go
> +	if s.repository22.LenRep() > 2 {
почему больше 2?

2022-04-06 07:12 UTC, staszigzag commented on service/serviceImpl.go
> +	delTask := new(repository.RepFilter)
что значит delTask? ты создаешь фильтр по которому будешь удалять, и лучше называть это фильтром

2022-04-06 07:12 UTC, staszigzag commented on service/service.go
> +	LenRep() int
сервису точно нужен такой метод? это же вроде логика репозитория

2022-04-06 07:12 UTC, staszigzag commented on service/serviceImpl.go
> +func (s *serviceImpl) LenRep() int {
а это зачем?

2022-04-06 07:15 UTC, Antoha2 commented on service/serviceImpl.go
> +	if s.repository22.LenRep() > 2 {
потому что с нуля считает

2022-04-06 07:16 UTC, Antoha2 commented on service/service.go
> +	LenRep() int
без этого не запускалась . конкретно этот метод залипуха , которая ничего не делает

2022-04-06 07:20 UTC, Antoha2 commented on transport/web/webImpl.go
> +	delId := new(service.SerTask)
это не понятно

2022-04-06 07:20 UTC, Antoha2 commented on service/serviceImpl.go
> +func (s *serviceImpl) LenRep() int {
без этого не запускалась . конкретно этот метод залипуха , которая ничего не делает

2022-04-06 08:19 UTC, staszigzag commented on service/serviceImpl.go
> +	if s.repository22.LenRep() > 2 {
не правда, len считает с 1

2022-04-06 08:23 UTC, Antoha2 commented on service/serviceImpl.go
> +	if s.repository22.LenRep() > 2 {
если ставить >3 , то работает некорректно . тогда можно 4 таски создать

2022-04-07 17:23 UTC, staszigzag requested changes

2022-04-07 17:23 UTC, staszigzag commented on repository/repositoryImplMap.go
> +		r.rep[index+1] = task
это же не будет правмльно работать( ты ключи которыми был айдишник заменяешь индексом

2022-04-07 17:25 UTC, staszigzag requested changes

2022-04-07 17:25 UTC, staszigzag commented on repository/repositoryImplMap.go
> +	delete(r.rep, delFilter.Id)
на удаление тоже лучше сделать проверку, что такой элемент существует

2022-04-08 05:47 UTC, staszigzag requested changes

2022-04-08 05:47 UTC, staszigzag commented on repository/repositoryImplMap.go
> +	for _, task := range r.rep {
перестань смотреть на мапу как на массив, и не надо ее постоянно перебирать

2022-04-08 05:50 UTC, staszigzag requested changes

2022-04-08 05:50 UTC, staszigzag commented on repository/repositoryImplMap.go
> +		sliceTask = append(sliceTask, r.rep[index])
что здесь вообще происходит?) это даже работать не будет адекватно...

2022-04-08 06:40 UTC, merged